name: Deploy VuePress Reco

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install vuepress
      run: |
        npm install @vuepress-reco/theme-cli@1.0.7 -g
        npm install

    - name: Generate
      run: npm run build

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: 120.55.98.102
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: ".vuepress/dist"
        target: "/var/www/html/twpfx"